theme: jekyll-theme-minimal

title: "ESwML 2024"
description: "Empowering Software through Machine Learning (ESwML)"
show_downloads: false
sidebar:
  - [2024](https://eswml.github.io/2024/2024.html) 

